# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
###
# Valid request
GET http://localhost:8080/v1/countries/BE/cities
Accept: application/json

###
# Will result in error since BEL has an invalid length, using the ServiceException.
GET http://localhost:8080/v1/countries/BEL/cities
Accept: application/json

###
# Will result in a Nullpointer, triggering general error mapper.
GET http://localhost:8080/v1/countries/NP/cities
Accept: application/json